parameters:
    guzzle.response.class: Guzzle\Http\Message\Response
    guzzle.client.class: Guzzle\Http\Client
    precash.baseurl: https://api.twitter.com/1.1


service:
    guzzle.precash.client:
        class: %guzzle.client.class%
        arguments: [%precash.baseurl%]