parameters:
#    site.example.class: Calldirek\SiteBundle\Example
    guzzle.response.class: GuzzleHttp\Message\Response
    guzzle.client.class: GuzzleHttp\Client
    precash.financial.services.config:
        base_url: "https://api.github.com"
        defaults:
            auth: ["empi2b@gmail.com", "g1thub2014"]
    precash.financial.services.partener.config:
        base_url: "https://api.github.com"
        defaults:
            auth: ["empi2b@gmail.com", "g1thub2014"]


services:
#    site.example:
#        class: %site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    financial.services:
        class: %guzzle.client.class%
        arguments: [%precash.financial.services.config%]

    financial.services.partner:
        class: %guzzle.client.class%
        arguments: [%precash.financial.services.partener.config%]
