customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

