security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
            #algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            #id: fos_user.user_manager
            id: fos_user.user_provider.username_email

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                success_handler: user.authentication.success_handler
            logout:
                path:   /logout
                target: /
                success_handler: user.logout.success_handler
            anonymous: ~
            #success_handler: security.authentication.customized_success_handler
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
