<?php

namespace Calldirek\UserBundle\Form\Handler;

use FOS\UserBundle\Form\Handler\RegistrationFormHandler as BaseHandler;
use FOS\UserBundle\Model\UserInterface;

class RegistrationFormHandler extends BaseHandler
{

    protected function onSuccess(UserInterface $user, $confirmation)
    {
        $user->setCreatedBy('Emmanuel');
        $user->setCreatedDate(new \DateTime('now'));
        $user->setLastUpdated(new \DateTime('now'));
        $user->setLastUpdatedBy('Emmanuel');
        parent::onSuccess($user, $confirmation); // TODO: Change the autogenerated stub
    }
}