parameters:
#    user.example.class: Calldirek\UserBundle\Example
    security.authentication.success_handler.class:  Calldirek\UserBundle\Services\LoginHandler

services:
#    user.example:
#        class: %user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    security.authentication.customized_success_handle:
        class:  %security.authentication.success_handler.class%
        public: false
        arguments: [@router, @security.context]
