parameters:
#    user.example.class: Calldirek\UserBundle\Example
    user.authentication.success_handler.class:  Calldirek\UserBundle\Services\LoginSuccessHandler
    user.logout.success_handler.class:  Calldirek\UserBundle\Services\LogoutSuccessHandler


services:
#    user.example:
#        class: %user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    user.authentication.success_handler:
        class: %user.authentication.success_handler.class%
        arguments: [@security.context, @router]

    user.logout.success_handler:
        class: %user.logout.success_handler.class%
        arguments: [@router]
